name: LinkedIn Scraper

on:
  schedule:
    - cron: '0 9 * * *'  # 9 AM UTC daily
    - cron: '0 21 * * *' # 9 PM UTC daily
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-22.04  # Explicitly use Ubuntu 22.04 instead of latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3 \
          libnspr4 \
          libatk1.0-0 \
          libatk-bridge2.0-0 \
          libcups2 \
          libdrm2 \
          libxkbcommon0 \
          libxcomposite1 \
          libxdamage1 \
          libxfixes3 \
          libxrandr2 \
          libgbm1 \
          libasound2
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        playwright install
        playwright install-deps
        
    - name: Run LinkedIn Scraper
      run: |
        python scraper.py
        
    - name: Commit and push results
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/
        git commit -m "Update scraped data [skip ci]" || echo "No changes to commit"
        git push